apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: k8s
  name: prometheus-k8s
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  - port: 10902
    protocol: TCP
    targetPort: http
    name: http-sidecar-metrics
  selector:
    app: prometheus
    prometheus: k8s
