apiVersion: v1
kind: Service
metadata:
  name: foo
  namespace: foremast-examples
  labels:
    app: foo
    appType: spring-boot
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: foo
---
## kubectl patch deploymentmonitor foo --type="merge" -p '{"spec":{"continuous":true}}' -n foremast-examples
apiVersion: deployment.foremast.ai/v1alpha1
kind: DeploymentMonitor
metadata:
  name: foo
  namespace: foremast-examples
spec:
  # Auto rollback or not when unhealthy detected
  remediation:
    option: AutoRollback

