apiVersion: v1
kind: Service
metadata:
  name: foo
  labels:
    app: foo
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: foo
---
# Configuration to let prometheus discover this service
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: foo
  labels:
    service-monitor: foo
spec:
  selector:
    matchLabels:
      app: foo
  endpoints:
  - port: http
    # Metrics URL, since it is using actuator, the following path is the default prometheus metrics path
    path: /actuator/prometheus
---
apiVersion: deployment.foremast.ai/v1alpha1
kind: DeploymentMonitor
metadata:
  name: foo
spec:
  # Auto rollback or not when unhealthy detected
  autoRollback: true
