apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: foo # Application Name
    appType: spring-boot # Application Type
  name: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
        version: v1
    spec:
      containers:
      - name: app
        image: docker.io/foremast/k8s-metrics-demo:0.1.0
        imagePullPolicy: Always
        env:
        - name: APP_NAME
          value: foo
        ports:
        - name: web
          containerPort: 8080
